# Numpy tutorial

In [1]:
# import the library to access its functions (obviously)

import numpy as np

## 1. Data types and attributes

> 1. Creating an array
> 2. Knowing the datatype of the array
> 3. Knowing the datatype of the values in the array
> 4. Knowing the size or the length of the array 

In [2]:
# ndarry()  or n-dimensional array is numpy's only data type
# 1

ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [3]:
# to get the data type of the array, use 
#2 

type(ar1)

numpy.ndarray

In [4]:
#3
# to get the data type of values inside the array use 

ar1.dtype

dtype('int32')

In [5]:
#4
# to get the dimension of the array, use
ar1.shape

(5,)

In [7]:
# to get the length or the size of the array, use 
ar1.size

5

# creating different type of arrays 
> 1. Array of ones
> 2. Array of zeros
> 3. Array of random values between 0 and 1
> 4. Array of random values between two specified integers 
> 5. Linear arrangement of values in an array

In [8]:
#  generates an array of ones with the dimensions 2 rows and 3 columns 
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# create an array that is 3 dimensional which is 4 in number only of ones with 5 columns, 2 rows 

ThreeDArrayOfOnes = np.ones((4,2,5))
ThreeDArrayOfOnes

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
# array of just zeros with 3 columns and 2 rows 

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# an even arrangement of values from 1 to 10 with a step or a difference of 2 from each consecutive one
'''
for instance :

print(np.arange(5,10,3))  is going to return 

5 , 8 because the only value that could be returned between 5 and 10 with a difference 3 starting from 5 is just 8 and no other.
The next difference would be giving out 11 which is out of the range -- which is 10 in this case.

So the code is basically telling the computer to find numbers from 5 (included) to 10(not included) and evenly space it such that the 
difference of 2 consecutive numbers in the output is 3
'''

range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [18]:
# random array is going to be created with start ,stop ,shape of the array 

'''
The code is going to tell the computer to create an array with random values in it ranging from 1 through 10, with the dimension
of the array being like 2 rows and 5 columns
'''

random_array = np.random.randint(1,10,(2,5))
random_array

array([[2, 3, 1, 1, 5],
       [2, 3, 7, 4, 9]])

In [25]:
# could creatw a random array of dim1,dim2,dim3,...,dimn

'''
the values in the array would always be in between 0 and 1 and the dimensions of the array gould go upto infinity 
'''

random_array3 = np.random.rand(5,2,4,2)
print(random_array3)


%timeit random_array3 # this is gonna return an approx time for the calculation and generation of this array

[[[[0.58221172 0.9508188 ]
   [0.93556015 0.41293266]
   [0.71840446 0.48852779]
   [0.38663905 0.53137779]]

  [[0.10566128 0.38098636]
   [0.80505425 0.4807067 ]
   [0.48248707 0.81115172]
   [0.17007907 0.10698057]]]


 [[[0.9290969  0.72777708]
   [0.7320244  0.96069177]
   [0.37902949 0.40822023]
   [0.87664519 0.21626631]]

  [[0.58862643 0.15319388]
   [0.26768679 0.68762942]
   [0.72743449 0.10006738]
   [0.84247593 0.48565463]]]


 [[[0.54769578 0.11898614]
   [0.71946956 0.09310723]
   [0.53715894 0.13369949]
   [0.24999773 0.53952969]]

  [[0.65195471 0.30811565]
   [0.61724769 0.72121225]
   [0.76395204 0.90803763]
   [0.02957547 0.79969378]]]


 [[[0.26308296 0.81513345]
   [0.33306838 0.65827413]
   [0.67350741 0.59602839]
   [0.34386726 0.71512846]]

  [[0.93205663 0.05475658]
   [0.51486035 0.78096196]
   [0.37799675 0.46567322]
   [0.08103363 0.71157819]]]


 [[[0.01301824 0.04870746]
   [0.91733982 0.52983455]
   [0.35376329 0.51025566]
   [0.97512798 0.10972247]]

  

In [26]:
# random seeds or pseudo random numbers 
np.random.seed(3)

# random.seed( a number ) is basically used to make the created array reproducable , exactly like what it was

ra1 = np.random.rand(5,4)
ra1

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761],
       [0.89294695, 0.89629309, 0.12558531, 0.20724288],
       [0.0514672 , 0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 , 0.59086282],
       [0.02398188, 0.55885409, 0.25925245, 0.4151012 ]])

In [28]:
r2 = np.random.rand(3,4)
r2

array([[0.28352508, 0.69313792, 0.44045372, 0.15686774],
       [0.54464902, 0.78031476, 0.30636353, 0.22195788],
       [0.38797126, 0.93638365, 0.97599542, 0.67238368]])

# viewing arrays and matrices

In [29]:
# finding unique elements in a numpy array 
np.unique(r2)

array([0.15686774, 0.22195788, 0.28352508, 0.30636353, 0.38797126,
       0.44045372, 0.54464902, 0.67238368, 0.69313792, 0.78031476,
       0.93638365, 0.97599542])

In [30]:
# returns the value(s) which is in the 0th index of a r2 , a numpy array
r2[0]

array([0.28352508, 0.69313792, 0.44045372, 0.15686774])

In [32]:
a4 = np.random.randint(1,10,(2,3,5))
a4


array([[[1, 3, 5, 6, 9],
        [9, 8, 6, 2, 2],
        [2, 6, 6, 8, 5]],

       [[4, 1, 1, 1, 1],
        [3, 3, 8, 1, 6],
        [1, 2, 5, 2, 3]]])

In [33]:
a4.shape , a4.ndim

((2, 3, 5), 3)

In [34]:
a4[0][0]
# returns the value in the 0th index of the 0th index of a4

array([1, 3, 5, 6, 9])

In [42]:
'''
say we need to get the 3rd value onwards from the 1st (0 being the beginning) index of both of the 2D arrays
'''
print(a4)
print('***********************')
print(a4[0:,1:,2])

[[[1 3 5 6 9]
  [9 8 6 2 2]
  [2 6 6 8 5]]

 [[4 1 1 1 1]
  [3 3 8 1 6]
  [1 2 5 2 3]]]
***********************
[[6 6]
 [8 5]]


# manipulating arrays and comparing 

In [44]:
# arithmatic
ones = np.ones(3)
ones
arr = np.ones(3)
arr

array([1., 1., 1.])

In [45]:
# adding 
arr + ones

array([2., 2., 2.])

In [46]:
# subtracting 
arr - ones

array([0., 0., 0.])

In [47]:
# multiplying
ar = np.array([2,5,4])
arr = np.array([3,2,4])
arr * ar

array([ 6, 10, 16])

In [48]:
arr/ar

array([1.5, 0.4, 1. ])

In [49]:
arr//ar

array([1, 0, 1], dtype=int32)

In [50]:
ar  ** 2

array([ 4, 25, 16], dtype=int32)

In [51]:
np.square(arr)

array([ 9,  4, 16], dtype=int32)

In [52]:
# adding two arrays , judt like the 'ar + arr'
np.add(ar ,arr)

array([5, 7, 8])

In [53]:
# exponential and log of 10 ansd natural log
print(np.exp(ar))
print(np.log10(ar))
print(np.log(ar))

[  7.3890561  148.4131591   54.59815003]
[0.30103    0.69897    0.60205999]
[0.69314718 1.60943791 1.38629436]


In [55]:
# returns the dot product of both arrays
print(np.dot(arr,ar))
print(np.dot(ar,arr))

32
32


## aggregation
performing a same operation in a number of things is the meaning of aggregation

In [71]:
ar

array([2, 5, 4])

In [72]:
sum(a4)

array([[ 5,  4,  6,  7, 10],
       [12, 11, 14,  3,  8],
       [ 3,  8, 11, 10,  8]])

In [73]:
np.sum(a4)

120

In [57]:
array = np.random.random(100000)   # generates an array of 100000 values in it (randomly)
array[:100] # returns the 1st 100
# array

array([0.12964145, 0.92697559, 0.616819  , 0.05153737, 0.36108038,
       0.88217274, 0.6444884 , 0.60692855, 0.95783665, 0.07570919,
       0.78218982, 0.99734184, 0.46356287, 0.85842624, 0.02470344,
       0.34716085, 0.16992056, 0.63355341, 0.45900967, 0.71228375,
       0.75062315, 0.45071879, 0.43286486, 0.72963869, 0.01491906,
       0.29337232, 0.03684451, 0.84865901, 0.0700406 , 0.02462825,
       0.16944607, 0.13480454, 0.76830429, 0.91515572, 0.48372204,
       0.4025768 , 0.9125374 , 0.35604595, 0.08684653, 0.94521149,
       0.34889897, 0.51194824, 0.91691685, 0.11725089, 0.32023361,
       0.51429349, 0.06959061, 0.10691977, 0.83407057, 0.35406301,
       0.98944194, 0.32417078, 0.19415439, 0.75958823, 0.95443559,
       0.96518729, 0.64556637, 0.19663952, 0.80281824, 0.92855999,
       0.41935851, 0.79996334, 0.46873578, 0.01032505, 0.64331144,
       0.31552015, 0.15790592, 0.46576606, 0.91445717, 0.01700614,
       0.94295837, 0.66388377, 0.35358019, 0.57729105, 0.29270

In [75]:
# std = var**1/2
np.std(arr) == np.var(arr)**(1/2)

True

In [76]:
high_var_array = np.array([1,100,100000,500000])
low_var_array = np.array([2,4,6,8])

In [77]:
np.var(high_var_array)

42492426862.6875

In [78]:
np.var(low_var_array)

5.0

 # reshaping and transposing 

In [79]:
#sample_ra = np.array((1,2,3,4,5),(13,23,34,45,23))

In [80]:
# transpose  switches the axes of the elements in an array 
a4.T
# this is done to do dot products in general .

array([[[1, 4],
        [9, 3],
        [2, 1]],

       [[3, 1],
        [8, 3],
        [6, 2]],

       [[5, 1],
        [6, 8],
        [6, 5]],

       [[6, 1],
        [2, 1],
        [8, 2]],

       [[9, 1],
        [2, 6],
        [5, 3]]])

In [81]:
a4

array([[[1, 3, 5, 6, 9],
        [9, 8, 6, 2, 2],
        [2, 6, 6, 8, 5]],

       [[4, 1, 1, 1, 1],
        [3, 3, 8, 1, 6],
        [1, 2, 5, 2, 3]]])

# dot product and element wise 

In [82]:
# syntax is np.dot(ar1 , ar2 )
# matrix multipliction
np.random.seed(3)
matrix1 = np.random.randint(1,20,(5,3))
matrix2 =np.random.randint(1,30,(5,3))
matrix1 , matrix2

(array([[11,  4,  9],
        [ 1, 11, 12],
        [10, 11,  7],
        [ 1, 13,  8],
        [15, 18,  3]]),
 array([[ 3, 29,  2],
        [20, 27,  6],
        [ 9, 15,  2],
        [11, 25, 28],
        [ 8, 25, 12]]))

to do matrix multiplication or dot product , the matrices have to be in an opposite to each other's shape . eg : ma1.shape = (3,5), ma.shape = (5,3)

In [83]:
# transpose the matrix 1 so that we could do the dot product of them
dot_matrix = np.dot(matrix1,matrix2.T)

In [84]:
np.sin(dot_matrix) , matrix2.T

(array([[-0.47555019, -0.95636712,  0.87758979,  0.98194647,  0.63676125],
        [ 0.41214595, -0.52905711, -0.07957859, -0.03533805, -0.25379421],
        [-0.98935386, -0.9765779 , -0.92344688,  0.19341424, -0.73316982],
        [ 0.15865243, -0.92003785,  0.08839871,  0.71491859,  0.98514108],
        [ 0.9425346 , -0.24519354,  0.52152528,  0.99999047,  0.32156532]]),
 array([[ 3, 20,  9, 11,  8],
        [29, 27, 15, 25, 25],
        [ 2,  6,  2, 28, 12]]))

# PRACTICAL APPLICATION 

# dot product exercise 

In [85]:
import pandas as pd 

In [86]:
np.random.seed(1)
sales_amt = np.random.randint(1,30,(5,4))
sales_amt

array([[ 6, 12, 13,  9],
       [10, 12,  6, 16],
       [ 1, 17,  2, 13],
       [ 8, 14, 29,  7],
       [26, 19, 21,  6]])

In [87]:
np.random.seed(0)
prices = np.random.randint(3,20,(4,1))
prices

array([[15],
       [18],
       [ 3],
       [ 6]])

In [88]:
details = pd.DataFrame(sales_amt,
                      index = ['mon','tue','wed','thur','fri'],
                      columns = ['almond','cashew','peanut','olive'])
details

almond  cashew  peanut  olive
mon        6      12      13      9
tue       10      12       6     16
wed        1      17       2     13
thur       8      14      29      7
fri       26      19      21      6

In [89]:
price = pd.DataFrame(prices,
                    index = ['almond','cashew','peanut','olive'],
                    columns = ['price ($)'])
price

price ($)
almond         15
cashew         18
peanut          3
olive           6

In [90]:
# now go for the dot product of the price with sales_amt 
result = np.dot(price.T,details.T)
result

array([[399, 480, 405, 501, 831]])

In [91]:
details['revenue ($)'] = result.reshape(5,1)
details

almond  cashew  peanut  olive  revenue ($)
mon        6      12      13      9          399
tue       10      12       6     16          480
wed        1      17       2     13          405
thur       8      14      29      7          501
fri       26      19      21      6          831

In [92]:
result.reshape(5,1)

array([[399],
       [480],
       [405],
       [501],
       [831]])

In [93]:
print('alhamdulillah ')

alhamdulillah 


# comparison operators 

In [97]:
ar, ar1

(array([2, 5, 4]), array([1, 2, 3, 4, 5]))

In [110]:
a1 >a2

array([[False, False, False],
       [False, False, False]])

In [111]:
a2 >a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [112]:
a1 = ar 
np.random.seed(1)
a2 = np.random.randint(1,20,(2,3))
a1,a2

(array([2, 5, 4]),
 array([[ 6, 12, 13],
        [ 9, 10, 12]]))

In [115]:
a2[1,0] = 1
a2

array([[ 6, 12, 13],
       [ 1, 10, 12]])

# sorting arrays 

In [117]:
random_ra = np.random.randint(1,200,(3,4))
random_ra 

array([[134,  80, 193, 145],
       [130,  72, 135,  26],
       [179,  21, 102, 147]])

In [122]:
random_ra  = np.random.randint(1,55,(4,3))

In [123]:
# to view the indeces with the highest value and the sort value,use argsort()
random_ra

array([[21, 12, 43],
       [29, 30, 15],
       [51,  5, 24],
       [24, 42, 50]])

In [124]:
np.sort(random_ra)

array([[12, 21, 43],
       [15, 29, 30],
       [ 5, 24, 51],
       [24, 42, 50]])

In [125]:
# returns the indeces with the highest value incrementally
np.argsort(random_ra)

array([[1, 0, 2],
       [2, 0, 1],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [127]:
np.argmin(random_ra,axis=0)     # axis =0 means rows 

array([0, 2, 1], dtype=int64)

In [128]:
np.argmax(random_ra,axis= 0)

array([2, 3, 3], dtype=int64)

# practical example numpy in action

In [130]:
# importing images are done in ndarray format 
from matplotlib.image import imread 
panda_img = imread('panda.png')
panda_img

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [135]:
panda_img[5]

array([[0.05490196, 0.10588235, 0.06666667],
       [0.05490196, 0.10588235, 0.06666667],
       [0.05490196, 0.10588235, 0.06666667],
       ...,
       [0.17254902, 0.13725491, 0.10196079],
       [0.17254902, 0.13725491, 0.10196079],
       [0.17254902, 0.13725491, 0.10196079]], dtype=float32)

In [139]:
np.min(panda_img,axis=0)

array([[0.01568628, 0.02352941, 0.01960784],
       [0.01176471, 0.01960784, 0.01568628],
       [0.00784314, 0.00784314, 0.        ],
       ...,
       [0.01568628, 0.01960784, 0.02745098],
       [0.01568628, 0.01960784, 0.02745098],
       [0.01568628, 0.01960784, 0.02745098]], dtype=float32)