# Tensorflow

Tensorflow is an open-source and free library used in the field of machine learning(ML).
It is developed and backed up by Google.
 
#  

### What's required from your part ???
> Basic knowledge of python and its syntax

> Basic knowledge in operating `ipynb` or i-python-notebooks

> Basic knowledge on matrices and vectors 

This is just a basic tutorial for beginners who are new to tensorflow. This tutorial is developed using python...With that said, let's get started

#  

## Importing the library

In [1]:
# we are importing tensorflow to this workspace and abbreviating it to tf for ease of use in our code.
import tensorflow as tf

#   

## Some basic things to understand before getting in

### Tensors:
A tensor is a generalization of a matrix or a vector to a higher dimension.

### Rank or Degree:
Rank or Degree of a tensor is the number of dimension of it. It could be used to know if the input data is a vector, matrix and so on.
For instance, if you're to find the rank of a matrix, then you'd get a 2 but if you're to look the rank of a vector, its going to be 1 and 0 for a scalar.

### Shape:
Shape of a tensor is the dimension of a tensor itself. If its a vector or n rows, then the shape is going to be (n,).
If its a matrix of n rows and m columns, then the output(shape) is going to be (n,m)

#  

In [2]:
# the following are some basic functions you might want to use

# to get the version of tensorflow you're currently using
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\hp\\Desktop\\ml\\env\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [2]:
# to create a simple tensor
string_tensor = tf.Variable('this is the string tensor',tf.string)
integer_tensor = tf.Variable(1234234345345,tf.int16)
floating_tensor = tf.Variable(12.234,tf.float32)
array_or_vector_of_strings = tf.Variable(['so','this','is','a','vector','of','strings'],tf.string)
matrix_of_string = tf.Variable([['hi','hello'],['greetings','my friend']],tf.string)

In [3]:
print('this is the preview or view of the matrix ')
print()
print(matrix_of_string)

this is the preview or view of the matrix 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'hi', b'hello'],
       [b'greetings', b'my friend']], dtype=object)>


In [4]:
print(tf.Variable([[1,2,3],[4,5,6]])) # this is another sample example of how it is

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>


In [5]:

# getting the shape of a tensor

print(string_tensor.shape)    # returns the shape of the above scalar called `string_tensor` which is actually 0
print(array_or_vector_of_strings.shape)  # returns the shape of the above vector which is (7,)
print(matrix_of_string.shape)    # returns the shape of the above matrix which is (2,2)

()
(7,)
(2, 2)


#  
### Creating and Reshaping 
The total number of elements in a tensor/matrix/vector is going to be the product of the values of its shape
You can reshape a tensor from its original dimension to a new one using
### `tf.reshape( initialTensor , dimensionToReshapeTo )` 

If you're to reshape an existing tensor to another with a different shape, you can also use 
### `tf.reshape( initTensor , [ n , -1 ] )` 
where `n` is any of the values in the dimension of the `initTensor` and `-1` is used to let Tensorflow know that the upcoming part of the shape of the tensor is going to be the product of the remaining values of the shape of the initTensor other than the one passed at `n`. On doing this, the other values will be multipied and the shape will be different.

For instance; if the shape of a tensor1 is (2,44,9) and if we are to reshape it like tf.reshape(tensor1 , [44,-1]) , 
the resultant tensor would be of the shape (44, 2 x 9 ) which is ( 44 , 18 ).
#   

In [6]:
# create a tensor full of ones of the shape (2,4,6) 
# this means that we are creating a tensor with just `1` in it and with 4 rows and 6 columns and there are going to be 2 of them

tensor_of_just_ones = tf.ones([2,4,6])
print(tensor_of_just_ones)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(2, 4, 6), dtype=float32)


In [7]:

# we are now going to reshape the tensor of just ones from [2,4,6] to [4,2,6]

print(tf.reshape(tensor_of_just_ones,[4,2,6]))

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(4, 2, 6), dtype=float32)


In [8]:

# when we put a negative sign in a `reshape-to`dimension, with an initial number, then tf will multiply the rest of the 
# values in its dimensions other than the one that you've already passed in as the first or the initial value for the new tensor

tf.reshape(tensor_of_just_ones,[6,-1])  # this returns a tensor which has 6 rows and 2*4 columns 

<tf.Tensor: shape=(6, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
# you can also have a tensor of just zeros, literally of any shape.

tensor_of_zeros = tf.zeros([5,2,8]) # tensor which contains 5 matrices of 2 rows and 8 columns for each
tensor_of_zeros

<tf.Tensor: shape=(5, 2, 8), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

#  
## There you go. You've successfully completed part one of this tutorial.
If you have any personal doubts, feel free to connect with me on [instagram](https://www.instagram.com/shimron.alakkal). 
See you guys in part 2 of this tutorial...